service: sls-fmwk-api-lambda-node-clienteunico
plugins:
  - serverless-domain-manager
  - serverless-pseudo-parameters
  #- serverless-plugin-log-retention
custom:
  myStage: ${opt:stage, self:provider.stage}
  domains:
    dev: api.dev.amauta.api-ngr.com
    qa: api.dev-qa.amauta.api-ngr.com
    prod: api.amauta.api-ngr.com
  securitygroups:
    dev:
      us-east-1: # virginia
        - sg-0df82d04ab647cec6
      us-west-2: # oregon
        - sg-0f46b6fce678e1d33
    qa:
      us-east-1: # virginia
        - sg-0df82d04ab647cec6
      us-west-2: # oregon
        - sg-0f46b6fce678e1d33
    prod:
      us-east-1: # virginia
        - sg-0da542fae4d132418
      us-west-2: # oregon
        - sg-031454b437717675e
  subnets:
    dev:
      us-east-1: # virginia
        - subnet-05fa503797db6ddbd
        - subnet-04121d97b4403661d
        - subnet-05706b8dce88e794d
        - subnet-0992bf8b0653731c2
      us-west-2: # oregon
        - subnet-03fba865cbd934b92
        - subnet-04a809ebde67f1bc4
        - subnet-056d0fe689ba24e86
        - subnet-054f6e4cd193e2c1c
    qa:
      us-east-1: # virginia
        - subnet-05fa503797db6ddbd
        - subnet-04121d97b4403661d
        - subnet-05706b8dce88e794d
        - subnet-0992bf8b0653731c2
      us-west-2: # oregon
        - subnet-03fba865cbd934b92
        - subnet-04a809ebde67f1bc4
        - subnet-056d0fe689ba24e86
        - subnet-054f6e4cd193e2c1c
    prod:
      us-east-1: # virginia
        - subnet-03af16f575ff0a1d8
        - subnet-03979aafff38480e7
        - subnet-0ae717cb262822206
        - subnet-09d5ecd7d1c8269e2
      us-west-2: # oregon
        - subnet-0f23c0e6e6c857978
        - subnet-0dd16d01daf96151a
        - subnet-0081b5e73dac08f9d
        - subnet-0fd4409cc2291e1ff
  customDomain:
    basePath: clienteunico/v1
    endPointType: 'regional'
    domainName: ${self:custom.domains.${self:custom.myStage}}
    stage: "${self:custom.myStage}"
    createRoute53Record: true
  settings:
    dev:
      ACCOUND_ID: "#{AWS::AccountId}"
      REGION: ${self:provider.region}
      AWS_TABLE: ngr-001-devcliu-table-clienteunico
      AWS_TABLE_CLIENTE: scr-amauta-table-cliente
      AWS_TABLE_PEDIDO_OSD: scr-osd-table-pedido-transaccion
      AWS_TABLE_AUTORIZACION: scr-002-amauta-table-autorizacion-historial
      QUEUE_NAME: ngr-002-devcliu-queue-clienteunico
      QUEUE_NAME_CLIENTE_CSV : ngr-002-devclienteunicocsv-queue-amauta
      QUEUE_NAME_PEDIDO_OSD_CSV : ngr-002-devpedidocsv-queue-osd
      S3_NAME: ngr-001-devcliu-clienteunico
      S3_NAME_VIRGINIA: ngr-001-devcliu-clienteunico-us-east-1
      S3_NAME_OREGON: ngr-001-devcliu-clienteunico-us-west-2
      S3_NAME_CLIENTE_UNICO_CSV: generacioncsvcliente-amauta
      S3_NAME_CLIENTE_UNICO_CSV_VIRGINIA: generacioncsvcliente-amauta-us-east-1
      S3_NAME_CLIENTE_UNICO_CSV_OREGON: generacioncsvcliente-amauta-us-west-2
      S3_NAME_PEDIDO_OSD_CSV: pedidocsv-osd
      S3_NAME_PEDIDO_OSD_CSV_VIRGINIA: pedidocsv-osd-us-east-1
      S3_NAME_PEDIDO_OSD_CSV_OREGON: pedidocsv-osd-us-west-2
      LAMBDA_REQUEST_VALIDATOR: oauth2-qadrp-lambdaAuthorizer
      LAMBDA_REQUEST_VALIDATOR_RESULT_TTL: 0
    qa:
      ACCOUND_ID: "#{AWS::AccountId}"
      REGION: ${self:provider.region}
      AWS_TABLE: ngr-001-qacliu-table-clienteunico
      AWS_TABLE_CLIENTE: scr-amauta-table-cliente
      AWS_TABLE_AUTORIZACION: scr-002-amauta-table-autorizacion-historial
      QUEUE_NAME: ngr-001-qacliu-queue-clienteunico
      QUEUE_NAME_CLIENTE_CSV : ngr-002-qaclienteunicocsv-queue-amauta
      S3_NAME: ngr-001-qacliu-clienteunico
      S3_NAME_VIRGINIA: ngr-001-qacliu-clienteunico-us-east-1
      S3_NAME_OREGON: ngr-001-qacliu-clienteunico-us-west-2
      S3_NAME_CLIENTE_UNICO_CSV: generacioncsvcliente-amauta
      S3_NAME_CLIENTE_UNICO_CSV_VIRGINIA: generacioncsvcliente-amauta-us-east-1
      S3_NAME_CLIENTE_UNICO_CSV_OREGON: generacioncsvcliente-amauta-us-west-2
      LAMBDA_REQUEST_VALIDATOR: oauth2-qadrp-lambdaAuthorizer
      LAMBDA_REQUEST_VALIDATOR_RESULT_TTL: 0
    prod:
      ACCOUND_ID: "#{AWS::AccountId}"
      REGION: ${self:provider.region}
      AWS_TABLE: ngr-001-prodcliu-table-clienteunico
      AWS_TABLE_CLIENTE: scr-amauta-table-cliente
      AWS_TABLE_AUTORIZACION: scr-002-amauta-table-autorizacion-historial
      QUEUE_NAME: ngr-001-prodcliu-queue-clienteunico
      QUEUE_NAME_CLIENTE_CSV : ngr-002-prdclienteunicocsv-queue-amauta
      S3_NAME: ngr-001-prodcliu-clienteunico
      S3_NAME_VIRGINIA: ngr-001-prodcliu-clienteunico-us-east-1
      S3_NAME_OREGON: ngr-001-prodcliu-clienteunico-us-west-2
      S3_NAME_CLIENTE_UNICO_CSV: generacioncsvcliente-amauta-prd
      S3_NAME_CLIENTE_UNICO_CSV_VIRGINIA: generacioncsvcliente-amauta-prd-us-east-1
      S3_NAME_CLIENTE_UNICO_CSV_OREGON: generacioncsvcliente-amauta-prd-us-west-2
      LAMBDA_REQUEST_VALIDATOR: oauth2-proddrp-lambdaAuthorizer
      LAMBDA_REQUEST_VALIDATOR_RESULT_TTL: 0
provider:
  name: aws
  runtime: nodejs20.x
  endpointType: REGIONAL
  enableAPIGLogs: true
  tracing:
    apiGateway: true
    lambda: true
  logRetentionInDays: 14
  environment: ${self:custom.settings.${self:custom.myStage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:DescribeTable"
        - "dynamodb:BatchWrite*"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.AWS_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.AWS_TABLE_CLIENTE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.AWS_TABLE_PEDIDO_OSD}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.AWS_TABLE_AUTORIZACION}"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
      Resource: 
        - "arn:aws:sqs:${self:provider.region}:*:${self:custom.settings.${self:custom.myStage}.QUEUE_NAME}"
        - "arn:aws:sqs:${self:provider.region}:*:${self:custom.settings.${self:custom.myStage}.QUEUE_NAME_CLIENTE_CSV}"
        - "arn:aws:sqs:${self:provider.region}:*:${self:custom.settings.${self:custom.myStage}.QUEUE_NAME_PEDIDO_OSD_CSV}"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_VIRGINIA}/*"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_OREGON}/*"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_CLIENTE_UNICO_CSV_VIRGINIA}"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_CLIENTE_UNICO_CSV_OREGON}"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_CLIENTE_UNICO_CSV_VIRGINIA}/*"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_CLIENTE_UNICO_CSV_OREGON}/*"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_PEDIDO_OSD_CSV_VIRGINIA}"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_PEDIDO_OSD_CSV_OREGON}"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_PEDIDO_OSD_CSV_VIRGINIA}/*"
        - "arn:aws:s3:::${self:custom.settings.${self:custom.myStage}.S3_NAME_PEDIDO_OSD_CSV_OREGON}/*"        

  vpc:
      securityGroupIds: ${self:custom.securitygroups.${self:custom.myStage}.${self:provider.region}}
      subnetIds: ${self:custom.subnets.${self:custom.myStage}.${self:provider.region}}
functions:  
  getHelloWorldHandler:
    handler: handlers/hola-mundo.handler
    timeout: 25
    events:
      - http:
          path: /holamundo
          method: get
          cors:
            origin: "*"
          authorizer:
            arn: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR}"
            resultTtlInSeconds: "${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR_RESULT_TTL}"
            type: request
            identitySource: method.request.header.Authorization         
    logRetentionInDays: 14
  getClientDocNode:
    handler: handlers/search-client.handler
    timeout: 25
    events:
      - http:
          path: /documento
          method: post
          cors:
            origin: "*"
          authorizer:
            arn: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR}"
            resultTtlInSeconds: "${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR_RESULT_TTL}"
            type: request
            identitySource: method.request.header.Authorization         
    logRetentionInDays: 14
  getPedidoOsdNode:
    handler: handlers/search-pedido.handler
    timeout: 25
    events:
      - http:
          path: /osd/consulta
          method: post
          cors:
            origin: "*"
          authorizer:
            arn: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR}"
            resultTtlInSeconds: "${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR_RESULT_TTL}"
            type: request
            identitySource: method.request.header.Authorization         
    logRetentionInDays: 14
  postRegDocClienteNode:
    handler: handlers/create-customer.handler
    timeout: 25
    events:
      - http:
          path: /cliente
          method: post
          cors:
            origin: "*"
          authorizer:
            arn: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR}"
            resultTtlInSeconds: "${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR_RESULT_TTL}"
            type: request
            identitySource: method.request.header.Authorization         
    logRetentionInDays: 14
  postRegPedidoNode:
    handler: handlers/create-pedido.handler
    timeout: 25
    events:
      - http:
          path: /pedido
          method: post
          cors:
            origin: "*"
          authorizer:
            arn: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR}"
            resultTtlInSeconds: "${self:custom.settings.${self:custom.myStage}.LAMBDA_REQUEST_VALIDATOR_RESULT_TTL}"
            type: request
            identitySource: method.request.header.Authorization         
    logRetentionInDays: 14
  generaClienteCsvNode:
    handler: handlers/sqs-create-customer.handler
    vpc:
      securityGroupIds: ${self:custom.securitygroups.${self:custom.myStage}.${self:provider.region}}
      subnetIds: ${self:custom.subnets.${self:custom.myStage}.${self:provider.region}}
  generaPedidoCsvNode:
    handler: handlers/sqs-create-pedido.handler
    vpc:
      securityGroupIds: ${self:custom.securitygroups.${self:custom.myStage}.${self:provider.region}}
      subnetIds: ${self:custom.subnets.${self:custom.myStage}.${self:provider.region}}
resources:
  Resources:
    #Create SQS 
    Queuengrclientecsv:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.settings.${self:custom.myStage}.QUEUE_NAME_PEDIDO_OSD_CSV}